<a href="https://colab.research.google.com/github/TheKoray18/Data-Manipulation/blob/main/VeriManip%C3%BClasyonu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

###Numpy Array Oluşturmak

- **Numpy Array**, numpy içerisinde yer alan **Listeler, Sözlükler** gibi veri tipidir.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
a = np.array([1,2,3,4])

a

array([1, 2, 3, 4])

In [ ]:
type(a)

numpy.ndarray

- **Sabit Tip Baskısı** ; Numpy array içerisinde, liste içerisinde **sadece 1 tip tutar**.

- Aşağıda ki arrayda ilk değerimiz **float** diğerleri **int** veri tipine sahiptir.

- Ama numpy **tüm değerleri float veri tipine çevirir**

In [ ]:
np.array([3.14, 4, 12,13])

array([ 3.14,  4.  , 12.  , 13.  ])

- Tipini ayarlayabilirz

In [ ]:
np.array([3.14, 4, 12,13], dtype = 'int')

array([ 3,  4, 12, 13])

In [ ]:
dizi = np.array([1,2,3,4])

- Bu arraydan 2 boyutlu bir başka array oluşturalım
- **"dizi"** arrayımız (4,1) olduğundan 2'ye 2'lik bir yeni dizi elde ettik

In [ ]:
dizi.reshape(2,2)

array([[1, 2],
       [3, 4]])

- 2 Boyutlu array oluşturma
- 4 sütunlu , 3 satırlı bir array oluşturduk.

In [ ]:
dizi2D = np.array([[1,2,3,4],[5,6,7,8],[9,8,7,6]])

dizi2D

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6]])

### np.zeros()

- 0'lardan oluşan array oluşturur.
- Çift parantez kullanırsak 2 boyutlu olur.

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.zeros((4))

array([0., 0., 0., 0.])

- **3'e 5'lik 0'lardan oluşan array** oluşturma

In [ ]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## np.ones()

- **1'lerden** oluşan bir array oluşturur

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones((4))

array([1., 1., 1., 1.])

- **3'e 5'lik 1'lerden oluşan array** oluşturma
- istersek **tipini değiştirebiliriz**

In [ ]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## np.empty()

- Boş bir array oluşturur.
- Sıfıra cok yakın değerlerdir.0'dırlar. Ondan boş matristir diyebiliriz

In [ ]:
np.empty((3,4))

array([[4.65115131e-310, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [6.92088927e-310, 8.60952352e-072, 6.81618461e-091,
        1.25669137e-071],
       [6.55036969e-043, 2.21658010e-056, 3.99910963e+252,
        1.46030983e-319]])

## np.arange(x,y,basamak)

-**X'den başlar, Y'ye kadar gider basamak kadar arttırarak** gider.

In [ ]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

## np.full()

- **Oluşturduğumuz dizi de hep aynı değer ile diziyi oluşturur.**

In [ ]:
np.full((3,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

## np.linspace(x,y,basamak)

- **X ve Y dahil olmak üzere , X'den başlayıp Y'ye kadar Y dahil ve o aralıkta basamak kadar sayıya böler**

- Yani ; **X ve Y dahil olacak şekilde X ile Y arasında Basamak değeri kadar sayı oluşturur.**

In [ ]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

##np.random.normal()

In [ ]:
np.random.normal(10,4,(3,4))

array([[ 7.03489555,  8.69279985, 12.25997801,  9.82053329],
       [11.35740859, 10.37065339, 11.45141326,  8.48906246],
       [12.54814232, 16.62509667, 11.51127882, 11.10510518]])

## np.random.randint(x,y)

- **X dahil X'den Y'ye kadar Random int sayı üretir**

In [ ]:
np.random.randint(0,10)

2

- **İstersek Size Verebiliriz**

In [ ]:
np.random.randint(0,10,(3,5))

array([[2, 2, 7, 7, 9],
       [2, 8, 9, 0, 2],
       [1, 9, 4, 4, 2]])

- **Eğer Başlangıç değeri vermezsek np başlangıç değerini 0 kabul eder.**
- **Aşağıdaki örnekte 0'dan 10'a kadar size =10 yani 10 tane random int değer üret dedik**

In [ ]:
np.random.randint(10,size = 10)

array([8, 7, 2, 0, 0, 8, 6, 1, 5, 5])

## Numpy Array Özellikleri

- **ndim** = _Boyut Sayısı_
- **Shape**= _Boyut Bilgisi_
- **Size** = _Toplam Elaman Sayısı_
- **dtype** = _Array Veri Tipi_

In [ ]:
a = np.random.randint(10,size = 10)

a

array([5, 5, 6, 9, 9, 5, 3, 9, 2, 9])

In [ ]:
print(f"Boyut Sayısı = {a.ndim}")
print(f"Boyut Bilgisi = {a.shape}")
print(f"Toplam Elaman Sayısı = {a.size}")
print(f"Array Veri Tipi = {a.dtype}")

Boyut Sayısı = 1
Boyut Bilgisi = (10,)
Toplam Elaman Sayısı = 10
Array Veri Tipi = int64


In [ ]:
b = np.random.randint(10, size = (3,5))

b

array([[7, 5, 4, 1, 0],
       [8, 1, 5, 0, 5],
       [8, 3, 8, 0, 3]])

In [ ]:
print(f"Boyut Sayısı = {b.ndim}")
print(f"Boyut Bilgisi = {b.shape}")
print(f"Toplam Elaman Sayısı = {b.size}")
print(f"Array Veri Tipi = {b.dtype}")

Boyut Sayısı = 2
Boyut Bilgisi = (3, 5)
Toplam Elaman Sayısı = 15
Array Veri Tipi = int64


## Yeniden Şekillendirme - Reshape

- **reshape() dizimizi 2 Boyutlu hale dönüştürür. Vektörden Matrise dönüştürür**

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

- **Yukarıdaki arrayımizi (3,3)'lük bir matrise çevirelim**

In [ ]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Birleştirme - Concatenate

- **axis parametresi eksenleri ifade eder.** 
   - **axis = 0 Satır bazlı birleştirme işlemi yapar.Default olarak axis = 0 gelir.**
   - **axis = 1 Sütun bazlı birleştirme işlemi yapar.**

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

 - **a ve b dizilerini birleştirelim**

In [ ]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

- **İki Boyutlu array oluşturalım**

In [ ]:
a = np.array([[1,2,3],
             [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

- **Sütun Bazlı Birleştirme İşlemi Yapalım**

In [ ]:
np.concatenate([a,a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Array Ayırma - Split

In [ ]:
x = np.array([1,2,3,99,99,3,2,1])

x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

- **x dizisini 3 parçaya bölerek ayıracağız**
- **[3,5] : Buradaki 3 indexi ifade eder. İlk 3 indexe kadar al dedik ayır dedik ve [1,2,3] değerini aldı.**
- **Daha Sonra 5 dedik yani 5. indexe göre al dedik ve [99,99] aldı**
- **[3,2,1] değerleri de tek kaldığı için onları da ayırmış olduk**

- **Biz [3,5] diyerek 2 index verdiğimizden dolayı 3 tane ayırma işlemi yapıyor. Eğer 3 tane index verseydik 4 tane ayırma işlemi yapardı**

In [ ]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

- **Ayırdığımız 3 tane array'ı tek tek almak için şu şekilde işlem yaparız**

In [ ]:
a,b,c = np.split(x,[3,5])

In [ ]:
a

array([1, 2, 3])

In [ ]:
b

array([99, 99])

In [ ]:
c

array([3, 2, 1])

- **Yukarıda gördüğünüz gibi ayırdığımız arrayları a,b,c değerlerine atayarak onları tek bir array olarak kullanabiliyoruz**

- **_İki Boyutlu Array_**

In [ ]:
m = np.arange(16).reshape((4,4))
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

- **Oluşturduğumuz 2 Boyutlu arrayımızı ayıralım

In [ ]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

- **Yukarıda gördüğümüz gibi 2 Boyutlu arrayımızı 2'ye "Yatayda" ayırdık.**

- **Yine ayırdığımız Arrayları tek bir arraymış gibi atayalım**

In [ ]:
alt,üst = np.vsplit(m,[2])

alt

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
üst

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

- **2 Boyutlu arrayımızı "Dikeyde" ayıralım**

In [ ]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

- **2 parçaya Dikeyde ayırdığımız arrayları tek tek başka değere atayalım**

In [ ]:
sağ,sol = np.hsplit(m,[2])

sağ

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [ ]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## Sıralama - Sort

In [ ]:
v = np.array([2,1,4,3,5])

v

array([2, 1, 4, 3, 5])

- **Dizimiz içerisindeki değerleri küçükten büyüğe doğru sıralar**
- **Ama dizimizin yapısını değiştirmez**

In [ ]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [ ]:
v

array([2, 1, 4, 3, 5])

- **Yukarıda gördüğümüz gibi dizimizin yapısı değişmedi.Şimdi _sort metodu_ ile küçükten büyüğe sıralayrak  dizimizin yapısını değiştirelim**

In [ ]:
v.sort()

v

array([1, 2, 3, 4, 5])

## Index Elemanlarına Erişmek


In [ ]:
m = np.random.randint(10, size = (3,5))

m

array([[0, 5, 3, 3, 8],
       [9, 4, 0, 6, 7],
       [8, 3, 2, 1, 1]])

- **Oluşturduğumuz 2 Boyutlu Arrayın 0. Satırında 0.Sütunda ki değeri alalım** 

In [ ]:
m[0,0]

0

- **1. Satırda, 1. Sütununda ki değeri alalım**

In [ ]:
m[1,1]

4

- **1. Satırda 4.Sütunda ki değeri alalım**

In [ ]:
m[1,4]

7

- **Arrayımızda ki değerleri değiştirebiliriz**
- **Örneğin yukarıda 1. Satırda 4. Sütunda ki 7 olan değeri 99 yapalım**

In [ ]:
m[1,4] = 99 

m

array([[ 0,  5,  3,  3,  8],
       [ 9,  4,  0,  6, 99],
       [ 8,  3,  2,  1,  1]])

## Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [ ]:
a = np.arange(20,30)

a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

- **0. indexten 3. indexe kadar git**

In [ ]:
a[0:3]

array([20, 21, 22])

- **3. indexten son indexe kadar git**

In [ ]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

- **1. indexten başlayarak son indexe kadar 2'şer 2'şer gitsin**

In [ ]:
a[1::2]

array([21, 23, 25, 27, 29])

###2 Boyutlu Slice İşlemleri

- Slice işlemlerini 2 boyutlu Array'lerde gerçekleştireceğimiz için, **İşlemlerimizi ",(virgül) " aracılığıyla satır ve sütun bazında yapacağız.**

   -  **m [ : , : ]** = Virgülün solunda ki işlemler **Satır üzerinde**,
   Virgülün Sağındaki işlemler ise **Sütun üzerinde** olur.

In [ ]:
m = np.random.randint(10,size = (5,5))

m

array([[8, 8, 7, 3, 5],
       [9, 9, 5, 8, 0],
       [0, 3, 7, 1, 5],
       [7, 1, 2, 3, 5],
       [8, 6, 2, 6, 5]])

- **Tüm satırları seçip, 0. sütunu alalım**
- Yani **İlk Sütuna** erişmiş olacağız.

In [ ]:
m[:,0]

array([8, 9, 0, 7, 8])

- **Şimdi ise Tüm Sütunları Seçip, 0. Satırı alalım**
- Yani **İlk Satıra** erişmiş olacağız

In [ ]:
m[0,:]

array([8, 8, 7, 3, 5])

- **Hem Satırla,Hem de Sütunlara Birlikte erişip belirli Elemanları seçelim**
- **O. Satırdan 2.indexteki Satırı al, 0. indexte ki Sütundan 3. indexte ki sütuna kadar alalım**

In [ ]:
m[0:2,0:3]

array([[8, 8, 7],
       [9, 9, 5]])

- **Tüm Satırları , ilk 2 sütunu alalım**

In [ ]:
m[:,0:2]

array([[8, 8],
       [9, 9],
       [0, 3],
       [7, 1],
       [8, 6]])

## Fancy Index ile Elemanlara Erişmek

In [ ]:
v = np.arange(0,30,3)

v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

- **v arrayının 1. indexindeki elemana ulaşalım**

In [ ]:
v[1]

3

-  **v arrayının 3. indexindeki elemana ulaşalım**

In [ ]:
v[3]

9

- **v arrayının 5. indexindeki elemana ulaşalım**

In [ ]:
v[5]

15

In [ ]:
[v[1],v[3],v[5]]

[3, 9, 15]

- Liste oluşturuyoruz.Bu listede v arrayınden almak istediğimiz değerlerin indexleri bulunuyor

In [ ]:
al_getir = [1,3,5]

al_getir

[1, 3, 5]

- **İçerisinde V arrayından almak istediğimiz elemanların index değerleri bulunana al_getir listesini V array içerisinde yazarsak bize o indexteki değerleri verir . Aşağıda gördüğümüz gibi**

In [ ]:
v[al_getir]

array([ 3,  9, 15])

### 2 Boyutta Fancy İşlemi

In [ ]:
m = np.arange(9).reshape((3,3))

m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
satır = np.array([0,1])
sütun = np.array([1,2])

satır, sütun

(array([0, 1]), array([1, 2]))

In [ ]:
m[satır,sütun]

array([1, 5])

## Koşullu Eleman İşlemleri



In [ ]:
v = np.array([1,2,3,4,5])

v

array([1, 2, 3, 4, 5])

- **Karşılaştırma operatörleri ile belirli işlemler gerçekleştireceğiz**

- **Örneğin, v Arrayının içersindeki değerlerin 5'den büyük olup olmadığını sorgulayalım**

- **Bize True,False sonuçlarını bir liste dönecek.**

- **SORGULAMA İŞLEMİ YAPACAĞIZ**

In [ ]:
v > 5

array([False, False, False, False, False])

- **v Arrayının içerisinde ki değerlerin 3'ten küçük olup olmadığını sorgulayalım**

In [ ]:
v < 3

array([ True,  True, False, False, False])

- **v < 3 için değerlerin Sağlayanları ya da sağlanmayanları dönen Boolean değerlere göre görebiliyoruz**
- **Şimdi ise v < 3 için sağlanan değerleri yani True olan v Arrayında ki 3'ten küçük olan değerleri almak istersek Fancy index ile alacağız**

In [ ]:
v[v < 3]

array([1, 2])

- **Böylelikle True olan değerleri almış olduk.**

In [ ]:
v[v != 4]

array([1, 2, 3, 5])

# Pandas

In [ ]:
import pandas as pd

## Series

- **Tek bir array gibi düşünebiliriz.**

In [ ]:
seri = pd.Series([11,22,33,44,55])

seri

0    11
1    22
2    33
3    44
4    55
dtype: int64

- **AXES**

- Serinin index bilgilerini bize verir.

- **0. indexten başlar.5. indexe kadar gider. Yani son index 4'tür.**

In [ ]:
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

### İndex İsimlendirilmesi

In [ ]:
seri = pd.Series([11,22,33,44,55], index=['a','b','c','d','e'])

seri

a    11
b    22
c    33
d    44
e    55
dtype: int64

In [ ]:
seri["a"]

11

- Slicin işlemi ile Serieslerden elemanlarına ulaşma.
- İndexlerine göre işlem yaparız.
- İndex isimlerine göre elemanlarına ulaşırız

In [ ]:
seri["a":"c"]

a    11
b    22
c    33
dtype: int64

### Sözlük(Dict) kullanarak Serie oluşturma

In [ ]:
sözlük = {'reg':10,'log':11,'cart':12}

seri = pd.Series(sözlük)

seri

reg     10
log     11
cart    12
dtype: int64

### Numpy Array ile Series oluşturma

In [ ]:
array = np.array([11,22,33,44,55])

seri = pd.Series(array)

seri

0    11
1    22
2    33
3    44
4    55
dtype: int64

###  Seride Eleman İşlemleri

In [ ]:
seri = pd.Series([121,200,150,99], index = ['reg','log','cart','rf'])

seri

reg     121
log     200
cart    150
rf       99
dtype: int64

#### Index

In [ ]:
seri.index

Index(['reg', 'log', 'cart', 'rf'], dtype='object')

#### Keys

- **keys()** , Keys kullanarakta index değerlerini alabiliriz

In [ ]:
  seri.keys()

Index(['reg', 'log', 'cart', 'rf'], dtype='object')

- **keys** kullanarak seriesi yazdırabiliriz.

In [ ]:
seri.keys

<bound method Series.keys of reg     121
log     200
cart    150
rf       99
dtype: int64>

- **items()** kullanarakta Serinin indexlere ve elemanlarına ulaşabiliriz.Dictionary'de olduğu gibi.

In [ ]:
list(seri.items())

[('reg', 121), ('log', 200), ('cart', 150), ('rf', 99)]

#### Fancy Eleman

- Fancy Yöntemi ile indexe göre eleman seçebiliriz

In [ ]:
seri[['reg','log']]

reg    121
log    200
dtype: int64

- Seri içerisindeki elemanları değiştirebiliriz.
- Fancy yöntemi ile index seçerek.

- 121 olan "reg" index değerini 130 olarak değiştirdik

In [ ]:
seri['reg'] = 130

seri['reg']

130

In [ ]:
seri['reg':'cart']

reg     130
log     200
cart    150
dtype: int64

## DataFrame

In [ ]:
array = np.array([11,22,33,44,55])

data = pd.DataFrame(array)

data

0
0  11
1  22
2  33
3  44
4  55

- **Columns ile Değişken isimlerine isimler verebiliyoruz**

In [ ]:
data = pd.DataFrame(array, columns = ['Değişken'])

data

Değişken
0        11
1        22
2        33
3        44
4        55

- **2 boyutlu Array ile DataFrame oluşturalım**

In [ ]:
m = np.arange(1,10).reshape((3,3))

m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
data = pd.DataFrame(m)

data

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

- **Columns parametresini kullanarak Değişken İsimleri verelim.**

In [ ]:
data = pd.DataFrame(m, columns = ['var1','var2','var3'])

data

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

- **Datamızın İstediğimiz Değişken İsimlerini "rename( )" ile de değiştirebiliriz**

In [ ]:
data.rename(columns={'var1':'deg1'})

deg1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

### İndex Bazında Eleman İşlemleri

In [ ]:
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

- Oluşturduğumuz numpy arrayleri üzerinden bir sözlük oluşturuyoruz

In [ ]:
sözlük = {'var1':s1,'var2':s2,'var3':s3}

sözlük

{'var1': array([1, 2, 9, 9, 6]),
 'var2': array([4, 2, 5, 3, 4]),
 'var3': array([4, 2, 7, 7, 0])}

- Oluşturduğumuz sözlük üzerinden de bir DataFrame elde edeceğiz

In [ ]:
df = pd.DataFrame(sözlük)

df

var1  var2  var3
0     1     4     4
1     2     2     2
2     9     5     7
3     9     3     7
4     6     4     0

- Datamızı 0'dan 1'e kadar alalım.Virgül fln yazmadığımız için direk yazdığımız için satır bazında işlem yapar

In [ ]:
df[0:1]

var1  var2  var3
0     1     4     4

- **İndexleri isimlendirme**

In [ ]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
df.index = ["a","b","c","d","e"]

df

var1  var2  var3
a     1     4     4
b     2     2     2
c     9     5     7
d     9     3     7
e     6     4     0

- index üzerinden işlemler yapalım.
- İndex değerlerine göre eleman seçelim
- Örneğin aşağıda **c'den e'ye kadar** alalım.

In [ ]:
df["c":"e"]

var1  var2  var3
c     9     5     7
d     9     3     7
e     6     4     0

#### Silme

- İndexler bazında silme işlemi yapalım
- a indexini datamızdan silelim 
- index bazında yani satır bazında silme işlemleri yaptığımızdan dolayı axis = 0 dedik.

In [ ]:
df.drop("a", axis = 0)

var1  var2  var3
b     2     2     2
c     9     5     7
d     9     3     7
e     6     4     0

- **c ile e** indexlerini silelim 

In [ ]:
df.drop(['c','e'], axis=0)

var1  var2  var3
a     1     4     4
b     2     2     2
d     9     3     7

### Değişken Bazında Eleman İşlemleri

- Basit bir değişken sorgusu yapalım.
- **v3** değişkenimiz **df datamızın** içerisinde mi demiş olduk.

In [ ]:
'v3' in df

False

- İstediğimiz değişken isimlerini for döngüsü kullanarak df içerisinde mi değil mi kontrol edelim

- **l adında bir liste oluşturduk.İçerisinde sorgulatmak istediğimiz değişken isimleri bulunuyor**

- **Daha sonra for döngüsü ile l listesi içerisinde gezerek "in df" diyerek sorgumuzu yapıyoruz**

In [ ]:
l = ['var1','var4','var2'] 

for i in l:
  print(i in df)

True
False
True


- **Datamızın "var1" değişkenini alalım.**

In [ ]:
df['var1']

0    27
1    27
2     4
3    17
4    14
5     4
6    29
7    24
8    19
9    12
Name: var1, dtype: int64

- **Datamızın "var1" değişkeninin 0'dan 4'e kadar olan gözlemlerini alalım**

In [ ]:
df['var1'][0:4]

0    27
1    27
2     4
3    17
Name: var1, dtype: int64

- **Datamızın var1 ve var2 değişkenlerinin 0'dan 4'e kadar olan gözlemlerini alalım**
- **Birden çok değişkeni almak istersek Fancy index yöntemini kullanırız.Yani df[ gözlem seçimi ] [ [ Almak istediğimiz değişkenler ] ]**

In [ ]:
df[0:4][['var1','var2']]

var1  var2
0    27     7
1    27    20
2     4     8
3    17    19

- **Datamıza yeni değişken ekleyeceğiz.Bu değişkeni de datamızdaki değişkenin değerlerini kullanarak yapacağız**

- **"var4" adında yeni bir değişken oluştralım.Bu değişkeni de var1 ve var2 değişkenin değerlerini çarparak oluşturalım**

In [ ]:
df['var4'] = df['var1'] * df['var2']

df

var1  var2  var3  var4
a     1     4     4     4
b     2     2     2     4
c     9     5     7    45
d     9     3     7    27
e     6     4     0    24

#### Silme

- index işleminde yaptığımız gibi silmek istediğimiz değişkenin ismini vererek siliyoruz.
- Değişken bazında silme işlemi yaptıdğımız için yani sütun bazında işlem yaptığımız için axis = 1 dedik

In [ ]:
df.drop('var4', axis = 1)

### Gözlem ve Değişken Seçimi - loc & iloc

In [ ]:
m = np.random.randint(1,30, size = (10,3))

df = pd.DataFrame(m, columns = ['var1','var2','var3'])

df

var1  var2  var3
0    27     7    13
1    27    20    15
2     4     8     1
3    17    19    26
4    14     5    21
5     4    11     1
6    29    12     8
7    24    27    23
8    19    21    27
9    12    27     4

#### loc

- Tanımlandığı şekliyle seçim yapmak için kullanılır.

- **Örneğin loc[ 0 : 3 ] diyerek 0'dan 3'e kadar değil 0 ve 3 dahil alarak işlem yapar loc**

In [ ]:
df.loc[0:3]

var1  var2  var3
0    27     7    13
1    27    20    15
2     4     8     1
3    17    19    26

- **0'dan 3'e kadar 3. gözlem dahil olarak indexleri aldık. Değişken seçerken de "Seçmek istediğimiz değişkenin ismini vermemiz gerekir.Çünkü loc ile tanımlananlara göre işlem yapar."**

- **Biz burada var1 ve var2 değişkenleri almak istediğimiz için virgülden sonra 'var1' : 'var2' yazdık.**

- **Eğer biz virgülden sonra var1 ve var2'yi seçmek isterken indexleme mantığı ile onların sütun değerlerini girseydik yani "var1" : "var2 " yerine " 0 " : " 1 " yazsaydık hata alırdık.Çünkü LOC bunu kabul etmiyor.**

In [ ]:
df.loc[0:3,'var1':'var2']

var1  var2
0    27     7
1    27    20
2     4     8
3    17    19

- **İstersek belirli bir gözlem aralığında istediğimiz değişkenin değerlerini alabiliriz**

In [ ]:
df.loc[0:3,'var3']

0    13
1    15
2     1
3    26
Name: var3, dtype: int64

#### iloc

- indexleme mantığı ile seçim yapar

- **Ayni indexi iloc ile almaya çalıştığımız da 3. indexteki değerler gelmez.Çünü iloc "e kadar" mantığıyla yani indexleme mantığıyla çalışır.**

In [ ]:
df.iloc[0:3]

var1  var2  var3
0    27     7    13
1    27    20    15
2     4     8     1

- **iloc kullanarak değişken seçerken de seçmek istediğimiz değişkenlerin (sütunların) sütun değerlerine göre indexleme mantığı ile seçim yaparız**

- **var1 ve var2'yi almak istiyorsak virgülden sonra onların sütun indexlerini yazmamız gerekiyor. Onların index değerleri 0 ve 1'dir. O yüzden O'dan 2'ye kadar girmemiz gerekiyor. Yani " 0 : 2 " yazarız.**

- **Eğer almak istediğimiz değişkenin sütun değerleri yerine değişken isimlerine göre işlem yapsaydık hata alırdık.Çünkü iloc bunu kabul etmiyor**

In [ ]:
df.iloc[0:3,0:2]

var1  var2
0    27     7
1    27    20
2     4     8

- **iloc kullanarak belirli bir gözlem aralığında istediğimiz değişkenin değerlerini almak için önce almak istediğimiz gözlem aralığını yazarız daha sonra almak istediiğimiz değişkenin ismini " [  ] " (köşeli parantez) içerisine yazmalıyız**

In [ ]:
df.iloc[0:3]['var3']

0    13
1    15
2     1
Name: var3, dtype: int64

In [ ]:
df['var1'][0:3]

0    27
1    27
2     4
Name: var1, dtype: int64

### Koşullu Eleman İşlemleri

In [ ]:
m = np.random.randint(1,30,size = (10,3))

df = pd.DataFrame(m, columns = ['var1','var2','var3'])

df

var1  var2  var3
0    10    25     8
1    18     7    18
2    16    17     2
3    24     8    22
4    16     6    29
5    23    20    22
6    16     5     1
7     8     9    29
8    16    20    13
9    29    26    16

- **Datamızın var1 değişkenindeki değerlerden 15'ten büyük olanların sorgusunu yapalım**

- Bildiğimiz üzere bize boolean değerler dönecek.

In [ ]:
df['var1'] > 15

0    False
1     True
2     True
3     True
4     True
5     True
6     True
7    False
8     True
9     True
Name: var1, dtype: bool

- **var1 değişkenindeki değerlerden 15'ten büyük olanları alalım.**

- **Yani sorgusu True olan elemanları alalım**

- **Tüm data üzerinden var1 değişkeninde ki değerlerden 15'ten büyük olanları almak istersek sorgumuzu df yazıp köşeli parantez içerisinde yapmamız lazım**

In [ ]:
df[df['var1'] > 15]

var1  var2  var3
1    18     7    18
2    16    17     2
3    24     8    22
4    16     6    29
5    23    20    22
6    16     5     1
8    16    20    13
9    29    26    16

- **Sadece var1 değişkeninde ki 15'ten büyük değerleri almak istersek, df [ " almak istediğimiz değişken " ] yazıp köşeli paranttez içerisinde sorgumuzu yaparız**

In [ ]:
df['var1'][df['var1'] > 15]

1    18
2    16
3    24
4    16
5    23
6    16
8    16
9    29
Name: var1, dtype: int64

- Aynı işlemi şu şekilde de yapabiliriz

- **Tüm data üzerinden sorgumuzu yazıp çıkan sonuçtan sadece " var1 " değişkeninde ki değerleri al demiş olduk.**

In [ ]:
df[df['var1'] > 15]['var1']

1    18
2    16
3    24
4    16
5    23
6    16
8    16
9    29
Name: var1, dtype: int64

- **Aynı değişken için farklı koşullar yazarakta sorguda bulunabiliriz.**

- **var1 değişkeninde ki değerlerden 15'ten büyük ve 25'ten küçük olan koşulu sağlayan değerleri tüm df üzerinden ver dedik**

In [ ]:
df[(df['var1'] > 15) & (df['var1'] < 25)]

var1  var2  var3
1    18     7    18
2    16    17     2
3    24     8    22
4    16     6    29
5    23    20    22
6    16     5     1
8    16    20    13

- **Yukarıda ki koşulu sağlayan değerlerden sadece var1 değişkeninde olanları almak istersek df['var1'] değişkenimizden sonra sorgumuzu köşeli parantez içerisinde yapıyoruz**

In [ ]:
df['var1'][(df['var1'] > 15) & (df['var1'] < 25)]

1    18
2    16
3    24
4    16
5    23
6    16
8    16
Name: var1, dtype: int64

- **Sorgumuzu sağlayan elemanları birden fazla istediğimiz değişkenler üzerinde de görebiliriz**

- **Tüm datamız üzerinden istediğimiz değişkenleri alacağımız için öncelikle df yazıp köşeli parantez açıp sorgumuzu yapıyoruz.Ardından hangi değişkenleri almak istiyorsak "Çift Parantez" içerisinde o değişken isimlerini yazıyoruz.**

- **NOT = Eğer birden fazla değişken almak istiyorsak " ÇİFT PARANTEZ " içerisinde yazarız.**

In [ ]:
df[df['var1'] > 15][['var1','var2']]

var1  var2
1    18     7
2    16    17
3    24     8
4    16     6
5    23    20
6    16     5
8    16    20
9    29    26

- **Birden fazla değişken üzerinde sorgu yapma işlemini loc kullanarakta yapabiliriz.**

- **loc kullanarakta sorgu yapabilir ve istediğimiz değişkenlerde bu sorguyu sağlayan değerlere ulaşabiliriz**

- **df.loc'tan sonra köşeli parantez içerisinde sorgumuzu gerçekleştirip, yine köşeli parantez içerisinde almak istediğimiz değişkenlerin isimlerini yazarız.**


In [ ]:
df.loc[df['var1'] > 15, ['var1','var2']]

var1  var2
1    18     7
2    16    17
3    24     8
4    16     6
5    23    20
6    16     5
8    16    20
9    29    26

##Birleştirme - Join

In [ ]:
m = np.random.randint(1,30, size = (5,3)) #5'e 3'lük boyutlu bir matris ouluşturduk.Değerleri de 1'den 30'a kadar random olacak.

df = pd.DataFrame(m, columns = ['var1','var2','var3'])

df

var1  var2  var3
0     7    15    25
1    28    23    25
2    25    10    12
3    20    16    15
4    20    25    16

- Yeni bir df elde edelim.İlk df'mizin değerlerine 30 ekleyerek yeni df2'yi elde edelim.

In [ ]:
df2 = df + 30

df2

var1  var2  var3
0    37    45    55
1    58    53    55
2    55    40    42
3    50    46    45
4    50    55    46

### Concat() ile Birleştirme

- Yukarıda elde ettiğimiz df ve df1 dataframelerimizi **concat()** ile birleştireceğiz.
- Birleştirme yapmak istediğimiz dataları liste içerisinde gönderiyoruz. "**[ df, df2 ]**"

In [ ]:
pd.concat([df,df2])

var1  var2  var3
0     7    15    25
1    28    23    25
2    25    10    12
3    20    16    15
4    20    25    16
0    37    45    55
1    58    53    55
2    55    40    42
3    50    46    45
4    50    55    46

- df ve df2 datalarımızı concat ile birleştirdik.
- Birleştirme sonucunda elde ettiğimiz yeni datamızın indexlerine baktığımızda bir index problemimiz var.
   - 0'dan 4'e kadar gidiyor ve yine 0'dan 4'e kadar gidiyor.

- **Bu problemi gidermek için " ignore_index " parametresine " TRUE " dememiz yeterli olacaktır.**

In [ ]:
pd.concat([df,df2], ignore_index = True)

var1  var2  var3
0     7    15    25
1    28    23    25
2    25    10    12
3    20    16    15
4    20    25    16
5    37    45    55
6    58    53    55
7    55    40    42
8    50    46    45
9    50    55    46

- Datamızın değişken isimlerine nasıl ulaşağımızı biliyoruz

In [ ]:
df2.columns

Index(['var1', 'var2', 'var3'], dtype='object')

- **İstediğimiz değişkenin ismini aşağıda ki gibi değiştirebiliriz**

- df2 datamızın " var3 " olan değişkenin ismini " deg3 " olarak değiştirdik.
- **df2.columns() ile değişken isimlerini almıştık.Bu bize 3 tane değer döndürdü.Çünkü 3 tane değişken ismimiz var. Bu sebeple yeni değişken ismi ataması yaparken " LİSTE İÇERİSİNDE " yeni değişken isimlerini yazarak, "DEĞİŞKEN SAYIMIZ KADAR " değer göndeririz.** 

In [ ]:
df2.columns = ['var1','var2','deg3']

df2

var1  var2  deg3
0    37    45    55
1    58    53    55
2    55    40    42
3    50    46    45
4    50    55    46

- Şimdi tekrar birleştirme işlemi yapalım

- "deg3" birleştirme yaptığımız 2 datamızda da olmadığından dolayı bunu problemli bir işlemmiş gibi algılayıp bir hata üretti.
- deg3 değişkenin df değişkenin de karşılığı yoktur. Olmadığından dolayı NaN değer ile doldurulmuş. O yüzden problemli bir birleştirme işlemi olmuştur.
- **Teknik olarak bir değişkenin birleştirme yaptığımız diğer datada bir karşılığı yoksa bunları birleştirmek doğru olmayacaktır.Çünkü "Aynı Bİlgiyi Taşımıyorlar".**

**NOT** = **"AYNI BİLGİYİ TAŞIMAYAN DEĞİŞKENLERİN OLDUĞU DATALARI BİRLEŞTİRMEK DOĞRU DEĞİLDİR !"**

In [ ]:
pd.concat([df,df2])

var1  var2  var3  deg3
0     7    15  25.0   NaN
1    28    23  25.0   NaN
2    25    10  12.0   NaN
3    20    16  15.0   NaN
4    20    25  16.0   NaN
0    37    45   NaN  55.0
1    58    53   NaN  55.0
2    55    40   NaN  42.0
3    50    46   NaN  45.0
4    50    55   NaN  46.0

- Bu problemi çözmek için **join** parametresine **inner** değerini veriyoruz.

- Bu şekilde birleştirme işlemi yaparken "iki datanın kesişimlerine göre" birleştirme işlemi yapar.
- **Birleştirme sonrası diğer datada karşılığı olmayan ve birleştirme sonrası NaN değerlere sahip olacak olan değişkenleri almaz!**


In [ ]:
pd.concat([df,df2], join = 'inner')

var1  var2
0     7    15
1    28    23
2    25    10
3    20    16
4    20    25
0    37    45
1    58    53
2    55    40
3    50    46
4    50    55

- Birleştirme sonrası diğer data karşlığı olmayan değişkenlerden birisini dahil etmek istiyorsak şu şekilde yaparız.

- **df ve df2 datalarımızın birleştirmelerini yaparız.Ardından " reindex( ) " ile içersine diğer datada karşılığı olmayan dahil etmek istediğimiz değişkenin olduğu datanın değişken isimlerini alıyoruz ( df.columns )**
- **Biz df2 datasında karşılığı olmayan var3 değişkenini almak istediğimiz için reindex( ) içerisine df.columns yazdık. Çünkü var3 df datası içerisinde**

In [ ]:
pd.concat([df,df2]).reindex(df.columns, axis = 1)

var1  var2  var3
0     7    15  25.0
1    28    23  25.0
2    25    10  12.0
3    20    16  15.0
4    20    25  16.0
0    37    45   NaN
1    58    53   NaN
2    55    40   NaN
3    50    46   NaN
4    50    55   NaN

### İleri Birleştirme Yöntemleri - Merge()

#### Birebir Birleştirme

- **Tüm elemanların birleştirme yapacağımız aynen yer almasıdır.**

In [ ]:
df1 = pd.DataFrame({'çalışanlar':['Ali','Veli','Ayşe','Fatma'],
                    'grup':['Muhasebe','Muhendislik','Muhendislik','IK']})

df1

çalışanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayşe  Muhendislik
3      Fatma           IK

In [ ]:
df2 = pd.DataFrame({'çalışanlar':['Ayşe','Ali','Veli','Fatma'],
                    'ilk_giriş':[2010,2009,2014,2019]})

df2

çalışanlar  ilk_giriş
0       Ayşe       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

- 2 tane veri setimiz var. 2 veri setinin de ortak değişkeni var: **Çalışanlar değişkeni**.
- Çalışkanlar değişkeninin elemanları df1 ve df2 veri setinde de aynıdır.Bu birebir birleştirme kategorisine girer.
- **merge() fonksiyonu ile birleştiririz**

In [ ]:
pd.merge(df1,df2)

çalışanlar         grup  ilk_giriş
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayşe  Muhendislik       2010
3      Fatma           IK       2019

- **merge( ) fonksiyonu "Birleştirmelerin hangi değişkenlere göre yapılacağını kendisi anlıyor"**

- Biz bunu kendimiz de verebiliriz.çalışanlar değişkenine göre birleştir diyebiliriz

In [ ]:
pd.merge(df1,df2, on = 'çalışanlar')

çalışanlar         grup  ilk_giriş
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayşe  Muhendislik       2010
3      Fatma           IK       2019

#### Çoktan Teke

In [ ]:
df3 = pd.merge(df1,df2)

df3

çalışanlar         grup  ilk_giriş
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayşe  Muhendislik       2010
3      Fatma           IK       2019

In [ ]:
df4 = pd.DataFrame({'grup':['Muhasebe','Muhendislik','IK'],
                    'mudur':['Caner','Mustafa','Berkcan']})

df4

grup    mudur
0     Muhasebe    Caner
1  Muhendislik  Mustafa
2           IK  Berkcan

- df3 veri setinde 3 değişken, df4 veri setinde ise 2 değişken vardır. Ortak değişkenleri **grup değişkenidir.**

- **df3 veri setinde ki "grup" değişkenimiz 4 değerde oluşuyor. df4 veri setinde ki "grup" değişkenimiz ise 3 değerden oluşuyor.**

   - **df3'te Çoklu Yapı, df4 ise Tekil bir yapı vardır.**

- Birleştirme işlemi yaparken çoklu yapıya göre birleştirme işlemi yapmış oldu.
- Yeni oluşturduğumuz Veri Setinde grup değişkenine baktığımızda 4 tane değer var.Çünkü **df3 çoklu yapıya sahipti** ve **df3'ün** **grup değişkenin** de  4 tane değer vardı.Şimdi yeni elde ettiğimiz veri setinde **mudur değişkenine** bir bakalım.

- df4 veri setinde tek Mustafa varken şimdi 2 tane Mustafa var. Biz birleştirme işlemini **grup** değişkenine göre ve **Çoklu Yapıya** göre birleştirme işlemi yaptığımız için ve Mustafa Mühendis grubunda olduğu için mudur değişkenin de bir tane da Mustafa oldu.




In [ ]:
pd.merge(df3,df4)

çalışanlar         grup  ilk_giriş    mudur
0        Ali     Muhasebe       2009    Caner
1       Veli  Muhendislik       2014  Mustafa
2       Ayşe  Muhendislik       2010  Mustafa
3      Fatma           IK       2019  Berkcan

# Çoktan Çoka

In [ ]:
df5 = pd.DataFrame({'grup':['Muhasebe','Muhasebe','Muhendislik','Muhendislik','IK','IK'],
                    'yetenekler':['matematik','excel','kodlama','linux','excel','yonetim']})

df5

grup yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  Muhendislik    kodlama
3  Muhendislik      linux
4           IK      excel
5           IK    yonetim

In [ ]:
df1

çalışanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayşe  Muhendislik
3      Fatma           IK

In [ ]:
pd.merge(df1,df5)

çalışanlar         grup yetenekler
0        Ali     Muhasebe  matematik
1        Ali     Muhasebe      excel
2       Veli  Muhendislik    kodlama
3       Veli  Muhendislik      linux
4       Ayşe  Muhendislik    kodlama
5       Ayşe  Muhendislik      linux
6      Fatma           IK      excel
7      Fatma           IK    yonetim

- Yukarıda gördüğümüz üzere Çalışanlar grubu çokladı. Yani arttı.
- **df1 veri setinde** **Ali'nin grubu muhasebeydi**. **df5 veri setinde muhasabenin 2 tane yeteneği vardı**. **"Excel ve Matematik"**.Bu yüzden **Ali muhasebe grubunda olduğu için 2 tane yeteneği olmuş oldu** ve **bir Ali fazladan yazılmış oldu**. **Çalışanlar değişkeninde**

## Toplulaştırma ve Gruplaştırma 

### groupby() : Gruplaştırma

- **Gruplama İşlemleri** = **Veri Setinde yer alan kategorik değişkenlerin gruplarının yakalanmaası ve bu grup özelinde bazı işlemler yapılması demektir.**

In [ ]:
df = pd.DataFrame({'gruplar':['A','B','C','A','B','C'],
                   'veri':[10,11,52,23,43,55]} , columns = ['gruplar','veri'])

df

gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

- Python arka tarafta bir nesne oluşturdu.df veri setine gitti groupby fonksiyonu ile  gruplar değişkenini yakaladı ve gruplar değişkeninin içerisinde yer alan kategori sınıflarını tuttu.

- Groupby fonksiyonu tek başına çalışamaz. Toplulaştırma fonskiyonu ile beraber çalışır.

In [ ]:
df.groupby("gruplar")

- Gruplar değişkeninde ki kategori sınıflarının yani A, B ve C'nin ortalamalarını aldık.

- Burada yaptığımız **mean()** işlemi bir **Toplulaştırma işlemidir.**

In [ ]:
df.groupby("gruplar").mean()

veri
gruplar      
A        16.5
B        27.0
C        53.5

### Toplulaştırma işlemleri

#### Agg() Fonksiyonu

In [ ]:
df = pd.DataFrame({'gruplar':['A','B','C','A','B','C'],
                   'değişken1':[10,23,33,22,11,99],
                   'değişken2':[100,253,333,262,111,969]} , columns = ['gruplar','değişken1','değişken2'])

df

gruplar  değişken1  değişken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

- **groupby() fonskiyonu ile veri setimizi gruplar değişkenimize göre ayırdık.Yani gruplar değişkenimize göre gruplara ayırdık. Gruplar değişkeninde ki kategorik değişkenlerin diğer "değişken1" ve "değişken2" değişkenlerinde ki istatistik değerlerini almak istiyoruz.Eğer almak istediğimiz istatistik değerlerini kendimiz belirlemek istiyorsak "agg()" fonskiyonu kullanırız.agg() fonskiyonu içerisine "liste halinde" almak istediğimiz istatistik işlemlerini veriyoruz**

- Biz **Kategorik değişken olan gruplar değişkenimizin**, **değişken1 ve değişken2 değişkenlerinde** ki değerlerinin ; **minimum değerlerini**, **median değerlerini** ve **maximum değerlerini** almak istediğimiz için **agg() fonskiyonu** içerisine **["min", np.median, max]** yazdık

In [ ]:
df.groupby('gruplar').agg(['min',np.median,max])

değişken1            değişken2            
              min median max       min median  max
gruplar                                           
A              10     16  22       100    181  262
B              11     17  23       111    182  253
C              33     66  99       333    651  969

- gruplar değişkenimizin değişken1 değişkeninde **minimum değerlerini**, değişken2 değişkeninde ise **maximum değerlerini** aldık.
- **agg() fonksiyonu** içerisinde **sözlük kullarak** **değişken1 değişkneninde ki minimum değerlerini** almak istediğimiz için **{'değişken1':'min'}**  **değişken2 değişkeninde ki maximum değerlerini** almak istediğimiz için de **{'değişken2':'max'}** dedik.

In [ ]:
df.groupby('gruplar').agg({"değişken1":'min','değişken2':'max'})

değişken1  değişken2
gruplar                      
A               10        262
B               11        253
C               33        969

####Filter() Fonksiyonu

- **filter() fonskiyonu içerisine bir fonskiyon alır**
- DataFrame üzerinde yaptığımız koşul işlemleri veya istatiksel koşul işlemleri gibi işlemler yaparken Pandas'ın bize sunduğu fonksiyonlar ile bunları hallediyoruz.Eğer bizim yapmak istediğimiz işlem Pandas'ın bize sağladığı fonksiyonlar ile çözemiyorsak o zaman biz kendimiz fonksiyon yazmak zorunda kalabiliriz.
- **Yazmış olduğumuz bu fonksiyonu filter() fonksiyonu ile kullanırız.**

In [ ]:
df = pd.DataFrame({'gruplar':['A','B','C','A','B','C'],
                   'değişken1':[10,23,33,22,11,99],
                   'değişken2':[100,253,333,262,111,969]} , columns = ['gruplar','değişken1','değişken2'])

df

gruplar  değişken1  değişken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

- Biz df veri setimizde bir koşul belirtmek istiyoruz.Bu koşul gruplar değişkeninde ki değerlerimizin değişken1 bazında standart sapması 9'dan büyük olanları almak istiyoruz. Fakat bunu Pandasın bize sağladığı bir fonksiyon ile çözemeyiz.
- O yüzden kendimiz bir fonksiyon yazacağız.Bu fonksiyon **değişken1** özelinde standart sapması 9'dan büyük olan **gruplar değişkeninde** ki değerleri bize verir.

In [ ]:
def MyStd(x):

  return x["değişken1"].std() > 9

 - Yazmış olduğumuz fonksiyonu **filter() fonskiyonu** ile kullanıyoruz. Yazdığımız fonskiyonu filter() içerisine yazıyoruz.

- yani siz bir fonksiyon oluşturup içine yazdığınız zaman ön tanımlı olan axis = 0 değerinden satırdaki her değeri alıp kendisi fonksiyona koyuyor ve size bir sonuc döndürüyor. bunuda size cıktı olarak veriyor.

In [ ]:
df.groupby('gruplar').filter(MyStd)

gruplar  değişken1  değişken2
2       C         33        333
5       C         99        969

#### transform() Fonksiyonu

- Transform() fonskiyonu vektörel bir fonksiyondur.Yani sütun bazında, değişkenler bazında, bütün değişkenler üzerinde bir işlem yapmak için kullanacağımız bir fonksiyon.Fakat bu fonksiyonun özelliği bizim istemiş olduğumuz bir fonksiyonu değişkenler üzerinde çalıştırabilmek.

- Bu sebeple fonksiyonel programlama özelliklerden olan lambda fonskiyonu kendi tanımladığımız bir fonksiyon olarak kullanırız.


In [ ]:
df_a = df.iloc[:,1:3]

df_a

değişken1  değişken2
0         10        100
1         23        253
2         33        333
3         22        262
4         11        111
5         99        969

- Değişkenlerimizin bulunduğu df_a datamıza tranform() fonksiyonu uyguluyoruz.

- df_a veri setimizdeki değişkenlerimizin değerlerini lambda fonksiyonu ile değişken değerlerinin kendisinden, değişkenin ortalamasını çıkararak bulduğumuz sonuç ile değiştiriyoruz.

- x burada bir değişkendir.Gezilecek olan sütunları, değişkenleri ifade eder.

In [ ]:
df_a.transform(lambda x: x-x.mean())

değişken1  değişken2
0      -23.0     -238.0
1      -10.0      -85.0
2        0.0       -5.0
3      -11.0      -76.0
4      -22.0     -227.0
5       66.0      631.0

- yani siz bir fonksiyon oluşturup içine yazdığınız zaman ön tanımlı olan axis = 0 değerinden satırdaki her değeri alıp kendisi fonksiyona koyuyor ve size bir sonuc döndürüyor. bunuda size cıktı olarak veriyor.

In [ ]:
def fonksiyon(x):

  return x-x.mean()

In [ ]:
df_a.transform(fonksiyon)

değişken1  değişken2
0      -23.0     -238.0
1      -10.0      -85.0
2        0.0       -5.0
3      -11.0      -76.0
4      -22.0     -227.0
5       66.0      631.0

In [ ]:
def funk2(x):

  result = x-x.mean()

  return result

df_a.transform(funk2)

değişken1  değişken2
0      -23.0     -238.0
1      -10.0      -85.0
2        0.0       -5.0
3      -11.0      -76.0
4      -22.0     -227.0
5       66.0      631.0

#### apply() fonksiyonu 

- apply() fonksiyonu, transform() ve filter() fonskiyonu gibi dataframe'in değişkenlerin üzerinde gezinme yeteneği olan ve toplulaştırma amacıyla kullanılabilecek olan fonksiyondur.

In [ ]:
df = pd.DataFrame({'gruplar':['A','B','C','A','B','C'],
                   'değişken1':[10,23,33,22,11,99],
                   'değişken2':[100,253,333,262,111,969]} , columns = ['gruplar','değişken1','değişken2'])

df

gruplar  değişken1  değişken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [ ]:
df.apply(np.sum)

gruplar      ABCABC
değişken1       198
değişken2      2028
dtype: object

In [ ]:
df.groupby('gruplar')

### Pivot Tablolar

- Veri setleri üzerinde bazı satır ve sütun işlemleri yaparak veri setini amaca uygun hale getirmek için kullanılan yapılardır.

- **groupby**'ın çok boyutlu versiyonu olarak düşünülebilir.

In [ ]:
import seaborn as sns 

titanic = sns.load_dataset('titanic')
titanic.head()

survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0         0       3    male  22.0  ...   NaN  Southampton     no  False
1         1       1  female  38.0  ...     C    Cherbourg    yes  False
2         1       3  female  26.0  ...   NaN  Southampton    yes   True
3         1       1  female  35.0  ...     C  Southampton    yes  False
4         0       3    male  35.0  ...   NaN  Southampton     no   True

[5 rows x 15 columns]

- **sex (cinsiyet) değişkenine göre** gruplandırma yaptık.
- Sürekli değişken olarakta **Survived** değişkenini seçtik.
- Cinsiyete göre gruplama işlemi yaptık.Survived değişkenine göre de ortalama aldık.

In [ ]:
titanic.groupby('sex')['survived'].mean()

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

- Çıktımızın bir dataframe olmasını istersek iki tane köşeli parantez yazmamız yeterli olacaktır.

In [ ]:
titanic.groupby('sex')[['survived']].mean()

survived
sex             
female  0.742038
male    0.188908

- Groupby operasyonunu genişleteceğiz.

- **Sex(cinsiyet) ve class** değişkenlerine göre groupby işlemi yaptık.O 2 değişkene göre grupladık.
- x eksenin de **sex değişkeni** y ekseninde **class kategorik değişkenin** sınıflarına göre bölüp kesişimlerinde birşeyler ifade etmiş olduk.

- Yani 2 tane kategorik değişkenimizi sürekli değişkendeki değerlerin ortalamasını alarak bir pivot tablo oluşturmuş olduk.

- **unstack()** Transpoze alır. Tablonun kolay okunmasını sağlar.


In [ ]:
titanic.groupby(['sex','class'])[['survived']].agg('mean').unstack()

survived                    
class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

#### pivot table ile

- **index** : Satır olarak değerlendiriyor. Gözlem biriminde olacak olan kategorik değişken

- **columns** : Sütunlar. Sütunda olacak olan kategorik değişken.

In [ ]:
titanic.pivot_table("survived", index = 'sex', columns = 'class')

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

- Biz Sürekli değişkenide tabloya eklemek ve diğer kategorik değişkenlere göre değerlendirme yapmak isteyelim diyelim
- Örneğin "age" değişkenimiz sürekli değişkenimizdir.**"age" değişkenimizle** beraber **"survived"** ve **"sex"** değişkenlerimizle beraber pivot tablo oluşturalım.
- **age değişkenimiz sürekli bir değişkendir**.ilk olarrak bunu **kategorik değişken** formatına dönüştürmemiz lazım

In [ ]:
titanic['age'].head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

- **age değişkenimizi** kategorik formata çevirelim.
- **cut() fonskiyonunu** kullararak age değişkenimizi bölerek kategorik formata dönüştürdük. age değişkeninde ki değerleri Liste içerisinde yazdığımız değerlere göre(aralıklara göre) bölmüş oldu. Şöyle ;

   - age değişkeninde **15 oaln değer**   -->   **(0,18]**
   - age değişkeninde **22 olan değer**   -->   **(18,90]**
   - age değişkeninde **38 olan değer**   -->   **(18,90]** değerlerini alır.

- Sürekli değişken olan **age değişkenini** 2 sınıflı olacak şekilde ayırarak  **kategorik değişkene** dönüştürmüş olduk.

In [ ]:
age = pd.cut(titanic['age'], [0,18,90])

age.head()

0    (18, 90]
1    (18, 90]
2    (18, 90]
3    (18, 90]
4    (18, 90]
Name: age, dtype: category
Categories (2, interval[int64]): [(0, 18] < (18, 90]]

In [ ]:
titanic.pivot_table("survived",index = ['sex', age], columns = 'class')

class               First    Second     Third
sex    age                                   
female (0, 18]   0.909091  1.000000  0.511628
       (18, 90]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 90]  0.375000  0.071429  0.133663

In [ ]:
pd.qcut(titanic['age'],2,labels=[1,2]).apply(lambda x: 'genc'if x>1 else 'yaşlı').head()

0    yaşlı
1     genc
2    yaşlı
3     genc
4     genc
Name: age, dtype: category
Categories (2, object): ['yaşlı' < 'genc']